services:
  web:
    build: .
    container_name: backend-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    environment:
      NODE_ENV: development